# -*- coding: utf-8 -*-
"""Análisis Churn - ABP - ISPC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdj9tqRjKkzn01h-7NWdg6jXPkWAoygk

**Institución**: Instituto Superior Politécnico de Córdoba (ISPC)

**Tecnicatura Superior**:  Ciencia de Datos e Inteligencia Artificial

**Espacio curricular**: Módulo Analista de Datos 2

**Docentes**: Donata Virginia DELFINI; Sol Del Valle FIGUEROA

**Integrantes**:

* Amaya, Brenda
* Amaya, Paula
* Cortez, Valeria
* Manrique Aguad, Agustin
* Martinez, Cristian
* Sudañez, Isaias Emanuel.

# **Análisis del Churn**
# **Comprensión del negocio**
## **Objetivos del negocio**
###**Contexto del problema**

Las empresas de telecomunicaciones deben gestionar grandes cantidades de clientes y buscar estrategias para mantenerlos en el tiempo. El abandono de un cliente, conocido como Churn, puede representar una pérdida de ingresos y generar la necesidad de captar nuevos clientes.

Los datos históricos sobre el comportamiento y las características de los clientes pueden utilizarse para identificar patrones asociados al abandono. El análisis de estos datos permite desarrollar modelos capaces de anticipar qué clientes presentan mayor probabilidad de abandonar el servicio.

Por este motivo, el proyecto busca utilizar técnicas de Ciencia de Datos para analizar el comportamiento de los clientes y desarrollar una solución predictiva orientada a la identificación del Churn.
###**Problema de negocio**

El problema consiste en la dificultad de identificar anticipadamente qué clientes tienen mayor probabilidad de abandonar el servicio.

Contar con una herramienta predictiva permitiría detectar clientes potencialmente propensos al abandono y proporcionar información útil para que la empresa pueda tomar decisiones y desarrollar acciones de retención.

La pregunta general que plantea el problema es: ¿Es posible identificar anticipadamente a los clientes con mayor probabilidad de abandonar el servicio utilizando la información disponible sobre ellos?

###**Stakeholders**

Los principales interesados en los resultados del proyecto son:

* Gerencia: necesita información que permita mejorar la toma de decisiones.
* Área de Marketing/Retención: puede utilizar las predicciones para orientar acciones de retención.
* Área de Atención al Cliente: puede utilizar la información para priorizar determinados clientes.
* Equipo de Ciencia de Datos: desarrolla el análisis y el modelo predictivo.

## **Evaluación de la situación actual**
### **Recursos disponibles**

Para el desarrollo del proyecto se cuenta con un dataset de clientes de una empresa de telecomunicaciones denominado telecom_dirty.csv.

El dataset contiene información relacionada con las características y el comportamiento de los clientes, incluyendo variables sobre antigüedad, renovación de contrato, utilización de servicios, llamadas al servicio de atención, consumo, cargos y roaming.

A diferencia de un dataset completamente limpio, el conjunto de datos utilizado para el proyecto contiene problemas de calidad introducidos deliberadamente, con el objetivo de trabajar posteriormente las etapas de identificación, limpieza y preparación de los datos.

Además, incorpora una variable temporal denominada RegistrationDate, correspondiente a la fecha de registro del cliente.

La información disponible permitirá realizar un análisis exploratorio y posteriormente desarrollar un modelo predictivo de Churn.

Los principales recursos de datos son:

* Dataset telecom_dirty.csv.
* Variable objetivo Churn.
* Variables numéricas relacionadas con el comportamiento y consumo de los clientes.
* Variables categóricas, incluyendo variables binarias.
* Variable temporal RegistrationDate.

Para el desarrollo del proyecto se utilizarán:

* Google Colab como entorno de trabajo.
* Python como lenguaje de programación.
* Pandas para la manipulación y análisis de datos.
* Matplotlib y Seaborn para las visualizaciones.
* Scikit-Learn para el desarrollo y evaluación de modelos.

### **Restricciones**

Las principales restricciones iniciales del proyecto son:

- El análisis estará limitado a las variables disponibles en el dataset.
- El dataset presenta problemas de calidad que deberán ser identificados durante el análisis exploratorio y tratados posteriormente durante la preparación de los datos.
- La información temporal disponible se limita a la variable RegistrationDate.
- El proyecto deberá desarrollarse utilizando las herramientas y técnicas abordadas durante la materia.
- El tiempo disponible estará condicionado por el calendario académico y las fechas de entrega.

### **Riesgos iniciales**
Entre los principales riesgos identificados al inicio del proyecto se encuentran:

- Que los datos disponibles no sean suficientemente representativos.
- Que los problemas de calidad del dataset afecten los resultados del análisis si no son correctamente identificados y tratados.
- Presencia de valores atípicos que puedan afectar el modelado.
- Desbalance entre clientes que abandonan y permanecen en el servicio.
- Selección inadecuada de variables para el modelo.
- Generación de Data Leakage durante la preparación o modelado.
- Overfitting del modelo.
- Bajo desempeño predictivo.

Estos riesgos serán revisados durante las siguientes etapas del proyecto y, cuando corresponda, se definirán estrategias para tratarlos.

Estos aspectos serán analizados y tratados en las etapas posteriores del proyecto.

## **Objetivos analíticos**
### **Objetivo de negocio**
Identificar anticipadamente a los clientes con mayor riesgo de abandono para generar información que permita apoyar la toma de decisiones y las estrategias de retención.

### **Objetivo analítico**
Desarrollar un modelo de clasificación capaz de predecir si un cliente abandonará o permanecerá en el servicio a partir de las características disponibles en el dataset.

La variable objetivo será Churn, que representa el abandono del cliente.

El problema corresponde a una clasificación binaria, donde se busca distinguir entre clientes que abandonan y clientes que permanecen en el servicio.

El dataset también contiene información temporal mediante la variable RegistrationDate. Esta variable será analizada durante el EDA y podrá ser considerada posteriormente para la creación de nuevas características, de acuerdo con los resultados obtenidos durante la preparación de los datos.

### **Pregunta analítica**
La pregunta principal que orientará el análisis es:

¿Es posible predecir si un cliente abandonará el servicio a partir de sus características y comportamiento registrado?

A partir de esta pregunta podrán plantearse posteriormente preguntas complementarias durante el EDA, como:

* ¿Qué características presentan los clientes que abandonan?
* ¿Qué variables tienen mayor relación con el Churn?
* ¿Qué características podrían ser relevantes para predecir el abandono?

Estas preguntas serán abordadas en las siguientes etapas.

En etapas posteriores se evaluará la utilización de modelos de clasificación, particularmente Regresión Logística, junto con las técnicas de validación y métricas estudiadas en la materia.

## **Plan de proyecto**
### **Criterios de éxito**
El proyecto se considerará exitoso si logra:

* Analizar correctamente la calidad y características del dataset.
* Identificar patrones relevantes relacionados con el Churn.
* Desarrollar un modelo de clasificación adecuado.
* Validar correctamente el modelo.
* Obtener métricas de evaluación satisfactorias.
* Interpretar los resultados y relacionarlos con el problema planteado.

Las métricas que se utilizarán posteriormente serán principalmente:

* Accuracy.
* Precision.
* Recall.
* F1-score.
* ROC-AUC.

### **Plan inicial del proyecto de datos**
El proyecto seguirá las principales etapas de la metodología CRISP-DM:

1. Comprensión del negocio: definición del problema, objetivos y criterios de éxito.
2. Comprensión de los datos: exploración inicial del dataset, identificación y clasificación de variables, estadísticas descriptivas y visualizaciones.
3. Preparación de los datos: identificación y tratamiento de valores faltantes, duplicados, inconsistencias, outliers y otros problemas de calidad detectados durante el EDA. También se considerará la transformación de la variable temporal y la selección de características.
4. Modelado: desarrollo de modelos de clasificación para predecir el Churn.
5. Evaluación: validación de los modelos y análisis de sus métricas.
6. Interpretación: análisis de los resultados y relación con el problema inicial.

La siguiente etapa a desarrollar será Comprensión de los Datos, donde se realizará el análisis exploratorio (EDA) del dataset telecom_churn.csv.

# Comprensión de los datos

* Análisis Exploratorio de Datos (EDA): Incluyendo la identificación y clasificación inicial de las variables numéricas y categóricas del dataset.
* Estadísticas descriptivas con visualizaciones

### Data Cleaning & Data profiling
"""

import pandas as pd

!gdown -O telecom_dirty.csv 1qD1clTmk0ZMbqD9H-Ecrbh4V9MnFnuVB

df = pd.read_csv("telecom_dirty.csv")
df

#Librerias

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from IPython.display import display, HTML

# Diagnostico preliminar (Data profiling)
"""
Script de Analisis preliminar
"""


def data_profiling_telecom(df: pd.DataFrame) -> None:
    """Ejecuta un diagnóstico preliminar"""

    display(("=== INFORMACIÓN GENERAL ==="))
    df.info()

    display(("=== ESTADÍSTICAS DESCRIPTIVAS ==="))
    display(df.describe(include="all"))

    display(("=== VALORES NULOS ==="))
    nulos_df = df.isnull().sum().to_frame(name="Cantidad Nulos")
    nulos_df["Porcentaje (%)"] = (df.isnull().sum() / len(df) * 100).round(2)
    display(nulos_df)

    display(("=== FILAS DUPLICADAS ==="))
    duplicados_df = pd.DataFrame(
        [{"Total Filas": len(df), "Duplicadas": df.duplicated().sum(), "Porcentaje (%)": round(df.duplicated().sum() / len(df) * 100, 2)}]
    )
    display(duplicados_df)


data_profiling_telecom(df)

"""
Script de Limpieza y Preparación de Datos: Telecom Churn & Series de Tiempo

Descripción: Este script resuelve problemas de duplicados, valores nulos, inconsistencias de texto,
             outliers lógicos e imputaciones cruzadas entre fechas de registro y semanas de antigüedad.
             Finalmente, organiza cronológicamente los datos y agrega columnas de agrupación mensual
             dejándolo 100% listo para modelos de Churn (ML) y Proyecciones de Ventas/Fuga (Series de Tiempo).
"""

def clean_telecom_data(df: pd.DataFrame) -> pd.DataFrame:
    """Limpia y prepara el dataset de Telecom Churn.

    """
    # Copia para evitar SettingWithCopyWarning
    df = df.copy()

    # -------------------------------------------------------------
    # 1. Eliminación de Duplicados Exactos
    # -------------------------------------------------------------
    initial_rows = len(df)
    df = df.drop_duplicates()
    duplicate_rows = initial_rows - len(df)
    print(
        f"[-] Eliminados {duplicate_rows} registros duplicados exactos."
        f" Nuevas dimensiones: {df.shape}"
    )

    # -------------------------------------------------------------
    # 2. Estandarización de Variables de Texto (Churn, ContractRenewal, DataPlan)
    # -------------------------------------------------------------
    binary_map = {
        "Yes": 1,
        "1": 1,
        "yes": 1,
        "True": 1,
        "Si": 1,
        "SI": 1,
        "YES": 1,
        "true": 1,
        "si": 1,
        "yess": 1,
        "No": 0,
        "0": 0,
        "False": 0,
        "NO": 0,
        "false": 0,
        "no": 0,
        "n0": 0,
    }

    for col in ["Churn", "ContractRenewal", "DataPlan"]:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().map(binary_map)
    print(
        "[✓] Estandarizadas columnas 'Churn', 'ContractRenewal' y 'DataPlan' a"
        " formato binario (0 y 1)."
    )

    # -------------------------------------------------------------
    # 3. Limpieza de Fechas e Imputación de Semanas (AccountWeeks)
    # -------------------------------------------------------------
    ref_date = pd.to_datetime("2026-08-28")

    def parse_date(x):
        if pd.isna(x):
            return pd.NaT
        x_str = str(x).strip()
        for fmt in (
            "%Y-%m-%d",
            "%d/%m/%Y",
            "%Y.%m.%d",
            "%m-%d-%Y",
            "%b %d, %Y",
            "%Y/%m/%d",
        ):
            try:
                return pd.to_datetime(x_str, format=fmt)
            except (ValueError, TypeError):
                continue
        try:
            return pd.to_datetime(x_str, errors="coerce")
        except (ValueError, TypeError):
            return pd.NaT

    df["RegistrationDate_clean"] = df["RegistrationDate"].apply(parse_date)

    # Inconsistencias lógicas
    df.loc[df["RegistrationDate_clean"] > ref_date, "RegistrationDate_clean"] = (
        pd.NaT
    )
    df.loc[df["AccountWeeks"] < 0, "AccountWeeks"] = np.nan

    # Imputaciones cruzadas
    mask_missing_date = (
        df["RegistrationDate_clean"].isna() & df["AccountWeeks"].notna()
    )
    df.loc[mask_missing_date, "RegistrationDate_clean"] = (
        ref_date
        - pd.to_timedelta(df.loc[mask_missing_date, "AccountWeeks"] * 7, unit="D")
    )

    mask_missing_weeks = (
        df["AccountWeeks"].isna() & df["RegistrationDate_clean"].notna()
    )
    df.loc[mask_missing_weeks, "AccountWeeks"] = (
        ref_date - df.loc[mask_missing_weeks, "RegistrationDate_clean"]
    ).dt.days // 7

    median_weeks = df["AccountWeeks"].median()
    df["AccountWeeks"] = df["AccountWeeks"].fillna(median_weeks)

    mask_still_no_date = df["RegistrationDate_clean"].isna()
    df.loc[mask_still_no_date, "RegistrationDate_clean"] = (
        ref_date
        - pd.to_timedelta(
            df.loc[mask_still_no_date, "AccountWeeks"] * 7, unit="D"
        )
    )

    df["AccountWeeks"] = df["AccountWeeks"].round().astype(int)
    print(
        "[✓] Corregidas inconsistencias de fechas e imputadas 'AccountWeeks' y"
        " 'RegistrationDate' cruzadas."
    )

    # -------------------------------------------------------------
    # 4. Limpieza de Variables de Consumo y Negocio
    # -------------------------------------------------------------
    # CustServCalls
    median_calls = df.loc[df["CustServCalls"] <= 10, "CustServCalls"].median()
    df.loc[df["CustServCalls"] > 10, "CustServCalls"] = np.nan
    df["CustServCalls"] = df["CustServCalls"].fillna(median_calls).astype(int)

    # DataUsage
    df.loc[(df["DataPlan"] == 0) & (df["DataUsage"].isna()), "DataUsage"] = 0.0
    median_data_usage_active = df.loc[
        (df["DataPlan"] == 1) & (df["DataUsage"] > 0), "DataUsage"
    ].median()
    df["DataUsage"] = df["DataUsage"].fillna(median_data_usage_active)

    # MonthlyCharge
    median_charge = df.loc[
        (df["MonthlyCharge"] >= 5.0) & (df["MonthlyCharge"] <= 500.0),
        "MonthlyCharge",
    ].median()
    df.loc[
        (df["MonthlyCharge"] < 5.0) | (df["MonthlyCharge"] > 500.0),
        "MonthlyCharge",
    ] = np.nan
    df["MonthlyCharge"] = df["MonthlyCharge"].fillna(median_charge)

    print("[✓] Tratadas anomalías en consumo, cobros y llamadas de servicio.")

    # -------------------------------------------------------------
    # 5. Estructuración y Ordenamiento Cronológico
    # -------------------------------------------------------------
    df["RegistrationMonth"] = (
        df["RegistrationDate_clean"].dt.to_period("M").astype(str)
    )
    df_sorted = df.sort_values(by="RegistrationDate_clean").reset_index(
        drop=True
    )
    df_final = df_sorted.drop(columns=["RegistrationDate"]).rename(
        columns={"RegistrationDate_clean": "RegistrationDate"}
    )

    cols_ordered = [
        "RegistrationDate",
        "RegistrationMonth",
        "AccountWeeks",
        "Churn",
        "ContractRenewal",
        "DataPlan",
        "DataUsage",
        "CustServCalls",
        "DayMins",
        "DayCalls",
        "MonthlyCharge",
        "OverageFee",
        "RoamMins",
    ]

    # Filtrar solo columnas existentes para evitar KeyError si falta alguna en el dataset
    cols_to_use = [col for col in cols_ordered if col in df_final.columns]
    df_final = df_final[cols_to_use]

    print("=== LIMPIEZA COMPLETADA CON ÉXITO ===")
    print(f"[✓] Dimensiones finales listas: {df_final.shape}")
    print("==============================================")

    return df_final

# DF ANALITICO
df_clean = clean_telecom_data(df)
df_clean.head()

# Reporte final (Data profiling post-limpieza)
"""
Reporte de Analisis posterior a la limpieza
"""


def final_report_telecom(df_clean: pd.DataFrame) -> None:

    display("=== REPORTE FINAL: INFORMACIÓN GENERAL ===")
    df_clean.info()

    display("=== REPORTE FINAL: ESTADÍSTICAS DESCRIPTIVAS ===")
    display(df_clean.describe(include="all"))

    display("=== REPORTE FINAL: VALORES NULOS ===")
    nulos_df = df_clean.isnull().sum().to_frame(name="Cantidad Nulos")
    nulos_df["Porcentaje (%)"] = (df_clean.isnull().sum() / len(df_clean) * 100).round(2)
    display(nulos_df)

    display("=== REPORTE FINAL: FILAS DUPLICADAS ===")
    duplicados_df = pd.DataFrame(
        [{"Total Filas": len(df_clean), "Duplicadas": df_clean.duplicated().sum(), "Porcentaje (%)": round(df_clean.duplicated().sum() / len(df_clean) * 100, 2)}]
    )
    display(duplicados_df)


final_report_telecom(df_clean)

"""### Identificacion y clasificacion de variables numerica y categoricas del data set

"""

# 1. Numéricas Continuas (Mediciones con decimales / float64)
num_continuas = df_clean[
    ["DayMins", "MonthlyCharge", "RoamMins", "DataUsage", "OverageFee"]
]

# 2. Numéricas Discretas (Conteos enteros / int64)
num_discretas = df_clean[["AccountWeeks", "CustServCalls", "DayCalls"]]

# 3. Categóricas Binarias / Nominales (Banderas 0 y 1)
cat_binarias = df_clean[["Churn", "ContractRenewal", "DataPlan"]]

# 4. Temporales / Ordinales (Fechas y Periodos)
temporales = df_clean[["RegistrationDate", "RegistrationMonth"]]

# ============================================================
# ANÁLISIS EXPLORATORIO DE DATOS (EDA) CORREGIDO Y ADAPTADO
# ============================================================
def eda_descriptivo_telecom(df_clean: pd.DataFrame) -> None:
    """Análisis exploratorio completo segmentado por dominio de variables."""

    # ─────────────────────────────────────────────────────
    # 1. IDENTIFICACIÓN Y CLASIFICACIÓN DE VARIABLES
    # ─────────────────────────────────────────────────────
    display("=" * 60)
    display("1. IDENTIFICACIÓN Y CLASIFICACIÓN DE VARIABLES")
    display("=" * 60)


    vars_num_continuas = [
        "DayMins",
        "MonthlyCharge",
        "RoamMins",
        "DataUsage",
        "OverageFee",
    ]
    vars_num_discretas = ["AccountWeeks", "CustServCalls", "DayCalls"]
    vars_numericas = (
        vars_num_continuas + vars_num_discretas
    )

    vars_binarias = ["Churn", "ContractRenewal", "DataPlan"]
    vars_temporales = [
        col
        for col in ["RegistrationDate", "RegistrationMonth"]
        if col in df_clean.columns
    ]
    vars_categoricas = (
        df_clean.select_dtypes(include=["object", "category"])
        .columns.difference(vars_temporales)
        .tolist()
    )

    print(
        f"\n Variables Numéricas Reales ({len(vars_numericas)}):"
        f" {vars_numericas}"
    )
    print(
        f"   - Continuas ({len(vars_num_continuas)}): {vars_num_continuas}"
    )
    print(
        f"   - Discretas ({len(vars_num_discretas)}): {vars_num_discretas}"
    )
    print(
        f" Variables Binarias/Nominales ({len(vars_binarias)}): {vars_binarias}"
    )
    print(f" Variables Categóricas Texto ({len(vars_categoricas)}): {vars_categoricas}")
    print(f" Variables Temporales ({len(vars_temporales)}): {vars_temporales}")

    # ─────────────────────────────────────────────────────
    # 2. ESTADÍSTICAS DESCRIPTIVAS DETALLADAS
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("2. ESTADÍSTICAS DESCRIPTIVAS - VARIABLES NUMÉRICAS")
    display("=" * 60)

    stats_numericas = df_clean[vars_numericas].describe().T
    stats_numericas["missing_%"] = (
        df_clean[vars_numericas].isnull().sum() / len(df_clean) * 100
    ).round(2)
    stats_numericas["skewness"] = (
        df_clean[vars_numericas].skew().round(3)
    )
    stats_numericas["kurtosis"] = (
        df_clean[vars_numericas].kurtosis().round(3)
    )
    display(stats_numericas)

    # ─────────────────────────────────────────────────────
    # 3. FRECUENCIAS - VARIABLES CATEGÓRICAS Y BINARIAS
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("3. FRECUENCIAS - VARIABLES CATEGÓRICAS Y BINARIAS")
    display("=" * 60)

    cols_cualitativas = vars_binarias + vars_categoricas
    for col in cols_cualitativas:
        if col in df_clean.columns:
            print(f"\n{col}:")
            freq_table = df_clean[col].value_counts().to_frame("Frecuencia")
            freq_table["Porcentaje (%)"] = (
                df_clean[col].value_counts(normalize=True) * 100
            ).round(2)
            display(freq_table)

    # ─────────────────────────────────────────────────────
    # 4. ANÁLISIS DE CORRELACIÓN
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("4. MATRIZ DE CORRELACIÓN")
    display("=" * 60)

    # Correlación aplicada únicamente a variables numéricas cuantitativas
    corr_matrix = df_clean[vars_numericas].corr()
    print("\nCorrelaciones cuantitativas más fuertes (|r| > 0.5):")

    corr_pares = []
    for i in range(len(corr_matrix.columns)):
        for j in range(i + 1, len(corr_matrix.columns)):
            val = corr_matrix.iloc[i, j]
            if abs(val) > 0.5:
                corr_pares.append({
                    "Variable 1": corr_matrix.columns[i],
                    "Variable 2": corr_matrix.columns[j],
                    "Correlación": round(val, 3),
                })

    if corr_pares:
        display(
            pd.DataFrame(corr_pares).sort_values(
                "Correlación", ascending=False
            )
        )
    else:
        print("No hay correlaciones estrictamente cuantitativas > 0.5")

    # ─────────────────────────────────────────────────────
    # 5. ANÁLISIS DE DISPERSIÓN Y OUTLIERS (IQR)
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("5. ANÁLISIS DE OUTLIERS (IQR)")
    display("=" * 60)

    outliers_info = []
    # IQR solo aplica conceptualmente a variables cuantitativas numéricas
    for col in vars_numericas:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        n_outliers = ((df_clean[col] < lower) | (df_clean[col] > upper)).sum()
        pct_outliers = (
            (n_outliers / len(df_clean) * 100) if len(df_clean) > 0 else 0
        )

        outliers_info.append({
            "Variable": col,
            "Q1": round(Q1, 2),
            "Q3": round(Q3, 2),
            "IQR": round(IQR, 2),
            "Límite Inferior": round(lower, 2),
            "Límite Superior": round(upper, 2),
            "N° Outliers": n_outliers,
            "% Outliers": round(pct_outliers, 2),
        })

    display(pd.DataFrame(outliers_info))

    # ─────────────────────────────────────────────────────
    # 6. VISUALIZACIONES - DISTRIBUCIONES NUMÉRICAS
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("6. DISTRIBUCIONES - HISTOGRAMAS (VARIABLES NUMÉRICAS)")
    display("=" * 60)

    n_cols = 4
    n_rows = (len(vars_numericas) + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 4 * n_rows))
    axes = axes.flatten()

    for idx, col in enumerate(vars_numericas):
        ax = axes[idx]
        df_clean[col].hist(bins=30, ax=ax, edgecolor="black", alpha=0.7)
        ax.set_title(f"Distribución: {col}", fontweight="bold")
        ax.set_xlabel(col)
        ax.set_ylabel("Frecuencia")

    for idx in range(len(vars_numericas), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.show()

    # ─────────────────────────────────────────────────────
    # 7. BOX PLOTS - DETECCIÓN VISUAL DE OUTLIERS
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("7. BOX PLOTS - DETECCIÓN DE OUTLIERS")
    display("=" * 60)

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 4 * n_rows))
    axes = axes.flatten()

    # Boxplots únicamente para variables cuantitativas
    for idx, col in enumerate(vars_numericas):
        ax = axes[idx]
        df_clean.boxplot(column=col, ax=ax)
        ax.set_title(f"Box Plot: {col}", fontweight="bold")
        ax.set_ylabel(col)

    for idx in range(len(vars_numericas), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.show()

    # ─────────────────────────────────────────────────────
    # 8. ANÁLISIS DE VARIABLES BINARIAS
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("8. DISTRIBUCIÓN DE VARIABLES BINARIAS")
    display("=" * 60)

    if vars_binarias:
        n_binary = len(vars_binarias)
        fig, axes = plt.subplots(1, n_binary, figsize=(5 * n_binary, 4.5))

        if n_binary == 1:
            axes = [axes]

        for idx, col in enumerate(vars_binarias):
            ax = axes[idx]
            value_counts = df_clean[col].value_counts().sort_index()

            # Mapeo genérico para etiquetas 0 y 1
            labels = [
                f"No ({val})" if val == 0 else f"Sí ({val})"
                for val in value_counts.index
            ]

            ax.bar(
                labels,
                value_counts.values,
                color=["#ff6b6b", "#51cf66"],
                edgecolor="black",
            )
            ax.set_title(f"{col}", fontweight="bold", fontsize=12)
            ax.set_ylabel("Frecuencia")

            for i, v in enumerate(value_counts.values):
                pct = v / len(df_clean) * 100
                ax.text(i, v, f"{pct:.1f}%", ha="center", va="bottom")

        plt.tight_layout()
        plt.show()

    # ─────────────────────────────────────────────────────
    # 9. HEATMAP DE CORRELACIÓN
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("9. MATRIZ DE CORRELACIÓN - HEATMAP")
    display("=" * 60)

    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(
        corr_matrix,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        center=0,
        square=True,
        linewidths=1,
        cbar_kws={"shrink": 0.8},
        ax=ax,
    )
    ax.set_title(
        "Matriz de Correlación - Variables Numéricas",
        fontweight="bold",
        fontsize=14,
    )
    plt.tight_layout()
    plt.show()

    # ─────────────────────────────────────────────────────
    # 10. ANÁLISIS TEMPORAL
    # ─────────────────────────────────────────────────────
    display("\n" + "=" * 60)
    display("10. ANÁLISIS TEMPORAL - REGISTROS POR MES")
    display("=" * 60)

    if "RegistrationMonth" in df_clean.columns:
        registros_por_mes = (
            df_clean["RegistrationMonth"].value_counts().sort_index()
        )
        print("\nRegistros por mes:")
        display(registros_por_mes.to_frame("Cantidad"))

        fig, ax = plt.subplots(figsize=(12, 5))
        registros_por_mes.plot(
            kind="bar", ax=ax, color="steelblue", edgecolor="black"
        )
        ax.set_title(
            "Distribución Temporal de Registros por Mes",
            fontweight="bold",
            fontsize=14,
        )
        ax.set_xlabel("Mes")
        ax.set_ylabel("Cantidad de Registros")
        ax.grid(axis="y", alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    else:
        print(
            "La columna 'RegistrationMonth' no está disponible en el DataFrame."
        )

    print("\n" + "=" * 60)
    print("ANÁLISIS EXPLORATORIO COMPLETADO")
    print("=" * 60)



eda_descriptivo_telecom(df_clean)